ENT-11138: proper error message when typing unsupported/unknown platform
cfengine/cf-remote pull request #83
Opened 2024-03-13 15:55 UTC by mineralsfree

Ticket: ENT-11138
Changelog: None

2024-03-15 14:43 UTC, larsewi approved these changes
```
$ git checkout master            
Already on 'master'
Your branch is up to date with 'origin/master'.
$ black --check cf_remote/spawn.py
All done! ✨ 🍰 ✨
1 file would be left unchanged.
$ gh pr checkout 83               
Switched to branch 'ENT-11138'
$ black --check cf_remote/spawn.py
would reformat cf_remote/spawn.py

Oh no! 💥 💔 💥
1 file would be reformatted.
```
Nice! Feel free to format with `black`. But still approved if you chose not to ✅

2024-03-15 19:36 UTC, olehermanse requested changes

2024-03-15 19:36 UTC, olehermanse commented on cf_remote/spawn.py
> +        return None
I did not run your code, but the error handling looks very different from what is on the line above;

```suggestion
    if not platform in aws_platforms:
        raise ValueError(
            "Platform '%s' does not exist.\nList of available platforms:\n%s"
            % (platform, "\n".join(cloud_data.aws_platforms.keys())))
```

Which may or may not be important. (Will the error messages look the same? Is there some special handling when catching the ValueErrors? Will the exit code be the same?)

So, either update them to be the same, or explain in the commit message how and why they are different.

2024-03-18 17:24 UTC, olehermanse approved these changes
Looks good now, thanks!

2024-03-18 17:24 UTC, merged