fix: handles non-existing versions when listing
cfengine/cf-remote pull request #93
Opened 2024-11-25 12:48 UTC by victormlg

2024-11-25 15:57 UTC, larsewi requested changes
Kan du legge til

```
Ticket: <TICKET_NO>
Signed-off-by <EMAIL>
```
i commit message?

Prøv disse stegene:
```
cd ~/ntech/cf-remote # Gå inn i cf-remote mappen
git checkout list # Pass på at du er på riktig branch
git commit --amend -s # Endre commit å legg til signatur (i.e., -s)
git push -f origin # Overskriv origin remote 
```

2024-12-02 08:55 UTC, larsewi approved these changes
Works great :rocket: 
```
$ cf-remote --version 1.2.3 list
Available releases: master, 3.24.x, 3.24.0, 3.21.x, 3.21.5, 3.21.4, 3.21.3, 3.21.2, 3.21.1, 3.21.0
cf-remote: CFEngine version '1.2.3' doesn't exist (yet).
```

2024-12-02 08:58 UTC, larsewi requested changes
Hold on... F-strings are not available in Python 3.5. You will need to format the string in another way. E.g.:

```python
user_error("CFEngine version '%s' doesn't exist (yet)." % version)
```

2024-12-02 14:27 UTC, larsewi approved these changes
Thanks :rocket:

2024-12-02 14:27 UTC, merged

2024-12-10 16:18 UTC, olehermanse commented on cf_remote/commands.py
> +    if version not in [rel.version for rel in releases.releases] :
```
if version and version not in [rel.version for rel in releases.releases]:
```

2024-12-10 16:22 UTC, olehermanse commented on cf_remote/commands.py
> +    if version not in [rel.version for rel in releases.releases] :
https://github.com/cfengine/cf-remote/pull/97